In [1]:
import numpy as np
from sklearn import model_selection
from sklearn import preprocessing
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# importing kagglehub to directly downloading the dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("alexteboul/diabetes-health-indicators-dataset")


# Load the CSV
df = pd.read_csv(f"{path}/diabetes_binary_5050split_health_indicators_BRFSS2015.csv")

In [3]:
# Display first few rows
df.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0

In [4]:
df.columns

Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

Data analysis and Preprocessing

In [5]:
columns_to_remove = ["Sex", "Age", "Income"]

df = df.drop(columns=columns_to_remove, errors="ignore")

In [6]:
df.describe()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Education
count,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000,70692.000000
mean,0.500000,0.563458,0.525703,0.975259,29.856985,0.475273,0.062171,0.147810,0.703036,0.611795,0.788774,0.042721,0.954960,0.093914,2.837082,3.752037,5.810417,0.252730,4.920953
std,0.500004,0.495960,0.499342,0.155336,7.113954,0.499392,0.241468,0.354914,0.456924,0.487345,0.408181,0.202228,0.207394,0.291712,1.113565,8.155627,10.062261,0.434581,1.029081
min,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,4.000000
50%,0.500000,1.000000,1.000000,1.000000,29.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,5.000000
75%,1.000000,1.000000,1.000000,1.000000,33.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,4.000000,2.000000,6.000000,1.000000,6.000000
max,1.000000,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,6.000000

In [7]:
standardScaler = preprocessing.StandardScaler()
columns_to_scale= ['BMI','GenHlth','MentHlth','PhysHlth']
df[columns_to_scale] = standardScaler.fit_transform(df[columns_to_scale])

In [8]:
x = df.drop(['Diabetes_binary'],axis = 1)
y = df['Diabetes_binary']

In [9]:
x_full,xtest_full,y_full,y_test_full = model_selection.train_test_split(x,y,test_size=0.1,random_state=32,shuffle=True)
#reducing dataset size to accomodate for processing.
x_train,x_test,y_train,y_test=model_selection.train_test_split(xtest_full,y_test_full,test_size=0.33,random_state=32)

#Converting pd dataframes to numpy arrays
x_train,x_test,y_train,y_test=x_train.to_numpy(),x_test.to_numpy(),y_train.to_numpy(),y_test.to_numpy()

m = y_train.shape
y_train = y_train.reshape(m[0],1)
y_test = y_test.reshape(y_test.shape[0],1)
x_train,x_test,y_train,y_test= x_train.T,x_test.T,y_train.T,y_test.T

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

(18, 4736)
(1, 4736)
(18, 2334)

Building the logistic regression model

In [10]:
def initialise(dim):
        '''Initialise the parameter values and bias values'''
        w = np.zeros((dim,1))
        b = 0
        print("w",w.shape)
        return w,b
        

def sigmoid(z):
    '''Compute sigmoid function'''
    sig = 1/(1+np.exp(-z))
    
    return sig

def cost_fn(w,b,x_train,y_train):
    '''Written cost function for both parameters and bias'''
    m = x_train.shape[1]
   
    
    A = sigmoid(np.dot(w.T,x_train)+ b)
   
    cst_fn = (-1)*(np.sum((np.log(A.T))*y_train+ (np.log(1-A.T))*(1-y_train)))/m
    
    
    

    dw = np.dot(x_train,(A-y_train).T)/m
    db = np.sum(A-y_train)/m
  

    gradient = {"dw":dw, "db": db}
   
    return cst_fn, gradient

Implementing Gradient descent

In [11]:
def gradient_descent(w,b,x_train,y_train,epochs,learning_rate):
    
    for i in range(epochs):
        costs = []
        cost,gradient = cost_fn(w,b,x_train,y_train)

        dw = gradient["dw"]
        db= gradient["db"]

        w = w- (learning_rate*dw)
        b= b - (learning_rate*db)

        if i%50==0:
            costs.append(cost)
    parameters = {"w":w,"b":b}
    gradient = {"dw":dw,"db":db}
    

    return  parameters, gradient, costs

Writing the predicting function

In [12]:
def predict(w,b,x_test):
    m = x_test.shape[1]
    y_prediction = np.zeros((1,m))
    w = w.reshape(x_test.shape[0],1)
    
    A = sigmoid(np.dot(w.T,x_test)+b)

    for i in range(A.shape[1]):
        if A[0,i]>=0.5:
            y_prediction[0,i]=1
        else:
            y_prediction[0,i]=0
    
    return y_prediction

Combining preceeding functions to make the logistic regression model

In [13]:
def logistic_regression(x_train, y_train,x_test,y_test,epochs=100,learning_rate=3):
    w,b = initialise(x_train.shape[0])

    parameters,gradient,costs= gradient_descent(w,b,x_train,y_train,epochs,learning_rate)
    w = parameters["w"]
    b = parameters["b"]
    
    y_pred_train = predict(w,b,x_train)
    y_pred_test = predict(w,b,x_test)

    accuracy_train= (100 - np.mean(np.abs(y_pred_train-y_train)*100))
    accuracy_test =(100 - np.mean(np.abs(y_pred_test-y_test)*100))

    print("Accuracy on training data", accuracy_train)
    print("Accuracy on test data", accuracy_test)
    return parameters

Training and testing the data.
The following step may take a while

In [14]:
model = logistic_regression(x_train, y_train,x_test,y_test,epochs=50,learning_rate=0.5)

w (18, 1)
Accuracy on training data 65.89949324324324
Accuracy on test data 65.46700942587833

The model has the following accuracy 
Accuracy on training data 72.50844594594595
Accuracy on test data 72.3650385604113

In [15]:

#Writing the data onto a file 
f1 = open("model_parameters.txt","w")
f1.write(str(model))
f1.close()